== Development Environment Setup

Like all software Library Weasel has a few dependencies that you need to have installed
on your development machine before you can work with it.

Library Weasel is a set of applications that are written to run together.
This allows Library Weasel to run as happily on your laptop or a single server or a distributed computing environment.

=== JDK
Currently the latest JDK 10 is required to build and develop plugins for Library Weasel.
See http://www.oracle.com/technetwork/java/javase/downloads/index.html for links to download
the latest version of the JDK.

=== IntelliJ Community Edition
IntelliJ is a popular Java/Kotlin IDE that is free and open source.
It's not required but is recommended for use when developing Library Weasel plugins.
See https://www.jetbrains.com/idea/download/ to download the Community Edition

=== Gradle
Gradle is a popular build tool for JVM projects that is used to build Library Weasel projects.
In fact all plugins are based on a Gradle plugin for building and supplying tasks and dependencies.
See https://gradle.org/ for download links and instructions on installing Gradle.

=== npm
npm is a package manager/build tool for JavaScript projects that is used to build the front end
components of Library Weasel plugins.
See https://www.npmjs.com/ for download links and instructions on installing npm.

== Testing your Environment

TODO add notes on checking out and building the sample plugin project
