= Plugins Explained
Library Weasel was designed with a modular plugin system at its core that allows users to create
extensions on both the server and frontend.  Because of this it can be a little daunting at first
to manage so many small projects instead of a single monolithic one, but this is what makes it relevant
to compare Library Weasel to a breadboard.  This page exists to explain each of the core application,
server, and developer plugins and projects.

== Non-Plugins
Not all projects related to Library Weasel are plugins, below are five projects that either deal with
the initialization of Library Weasel or aid in the development of Library Weasel plugins.  One important
thing to note is that all of the projects under this heading are not OSGi bundles while all true
plugins are OSGi bundles and are ran in the context of OSGi these are meant to be used outside of this
context.

=== library-weasel-server
This project is used to start up Library Weasel with only its server and web plugins installed.
It can be thought of as the "production" build since it doesn't include any development plugins.

=== library-weasel-developer
This project does all that `library-weasel-server` does but also starts up a JavaFX desktop application
that provides additional functionality that can benefit users while they are developing on their
local machines.  In fact Library Weasel is designed so that it is likely that some people will only
use this project since they will always work with Library Weasel on their local machine.  The desktop
application can also run plugins that are used not just to help with developing server side plugins.
Library Weasel can be viewed as a little androgynous in this regard since it doesn't make you decide
between server or desktop if you are working on data sets that benefit from either.

=== library-weasel-core
This project is what both `library-weasel-server` and `library-weasel-developer` use to start the
actually Vert.x and OSGi instances that Library Weasel is build around.  If you wanted to build your
own project similar to the two above this project is what you would use to actually integrate with
Library Weasel.

== library-weasel-gradle-plugin
Despite its name library-weasel-gradle-plugin isn't a Library Weasel plugin but instead is a Gradle
plugin that is be used by Library Weasel plugins.

== library-weasel-developer-gradle-plugin
Similar to library-weasel-gradle-plugin this project is used as a Gradle plugin to help with the
development of Library Weasel plugins that add functionality to the desktop JavaFX library-weasel-developer
application.

== Core Plugins


== Development Plugins

