= Plugins Explained
Library Weasel was designed with a modular plugin system at its core that allows users to create
extensions on both the server and frontend.  Because of this it can be a little daunting at first
to manage so many small projects instead of a single monolithic one, but this is what makes it relevant
to compare Library Weasel to a breadboard.  This page exists to explain each of the core application,
server, and developer plugins and projects.

== Non-Plugins
Not all projects related to Library Weasel are plugins, below are five projects that either deal with
the initialization of Library Weasel or aid in the development of Library Weasel plugins.  One important
thing to note is that all of the projects under this heading are not OSGi bundles while all true
plugins are OSGi bundles and are ran in the context of OSGi these are meant to be used outside of this
context.

=== library-weasel-server
Is used to start up Library Weasel with only its server and web plugins installed.
It can be thought of as the "production" build since it doesn't include any development plugins.

=== library-weasel-developer
Does all that `library-weasel-server` does but also starts up a JavaFX desktop application
that provides additional functionality that can benefit users while they are developing on their
local machines.  In fact Library Weasel is designed so that it is likely that some people will only
use this project since they will always work with Library Weasel on their local machine.  The desktop
application can also run plugins that are used not just to help with developing server side plugins.
Library Weasel doesn't make you decide between designing exclusively for either the server or desktop
if you are working with data sets that benefit from either or both in different ways.

=== library-weasel-core
This project is what both `library-weasel-server` and `library-weasel-developer` use to start the
actually Vert.x and OSGi instances that Library Weasel is build around.  If you wanted to build your
own project similar to the two above this project is what you would use to actually integrate with
Library Weasel.

=== library-weasel-gradle-plugin
Despite its name library-weasel-gradle-plugin isn't a Library Weasel plugin but instead is a Gradle
plugin that is be used by Library Weasel plugins.  This project contains the `copyPlugin` task as well
as manages the application of other common gradle plugins and also defines the `coreDeps` and
`pluginDeps` lists of external dependencies that are used to copy these deps as well as make them
available as references by other plugins.

=== library-weasel-developer-gradle-plugin
Similar to `library-weasel-gradle-plugin` this project is used as a Gradle plugin to help with the
development of Library Weasel plugins that add functionality to the desktop JavaFX library-weasel-developer
application.  This plugin applies the `library-weasel-gradle-plugin` to all developer plugins and
adds the `devPluginDeps` list of developer dependencies used when building `library-weasel-developer`
and for reference when developer other plugins.

== Core Plugins
The following plugins are all OSGi bundles that provide functionality that can be considered core to
Library Weasel.  Mostly involving OSGi, Vertx, Xodus, authentication, and instance management.

=== library-weasel-vertx


=== library-weasel-vertx-api


=== library-weasel-xodus


=== library-weasel-auth


=== library-weasel-servo


=== library-weasel-instance-files


=== library-weasel-plugin-autoloader


=== library-weasel-start-page


=== library-weasel-user


== Development Plugins
The following plugins are all OSGi bundles that provide functionality that is used by default by the
`library-weasel-developer` project.

=== multi-page-display
Supplies the tab pane that Library Weasel Developer uses.

=== library-weasel-developer


=== library-weasel-developer-console


=== library-weasel-developer-util


=== library-weasel-developer-api


=== library-weasel-developer-icons


=== library-weasel-developer-osgi


=== library-weasel-developer-script


=== library-weasel-developer-user
