= Third Party Dependencies

Library Weasel, like much free software, builds on top of already existing tools and libraries.
This page lists out and describes some of the most important of these projects.  Many other projects
are used but below are the ones that almost every Library Weasel plugin are likely to use.

== Undertow
Undertow is a small web server written in Java that can easily be embedded and extended.
It is used by Library Weasel as it's main web server and you may have noticed the WebPlugin interface
uses Undertow's Handler interface directly.
http://undertow.io/

== Project Reactor
Project Reactor is a reactive programming library for the JVM.
It is typically used in API to handle blocking calls more explicitly.
https://projectreactor.io/

== Gradle
Gradle is a build tool for the JVM.  I find it easier to work with and extend than other tools such as
maven or ant.  Several projects related to Library Weasel are simply plugins for Gradle.
https://gradle.org/

== Kotlin
Kotlin is an alternative statically typed JVM language that focuses on clean and maintainable code.
Since it comes from JetBrains it also focuses on being toolable and is well supported by the community
edition of IntelliJ IDEA.
https://kotlinlang.org/

== Groovy
Groovy is a scripting language for the JVM that is easy to embed into applications.  It is mainly used
by the library-weasel-developer-script plugin to allow users to run scripts within a Library Weasel
instance.
http://groovy-lang.org/

== JUnit 5
JUnit 5 is the latest version of the very popular JUnit testing framework.
By default all projects that use the Library Weasel Gradle plugin are automatically set up to use JUnit 5.
https://junit.org/junit5/

== KotlinTest
KotlinTest is a testing tool inspired by ScalaTest for the Kotlin programming language.
https://github.com/kotlintest/kotlintest

== Hyperapp
Hyperapp is a frontend javascript library that focuses on making it easier to create reactive and
maintainable UIs.
https://hyperapp.js.org/

== Bulma
Bulma is a CSS framework similar to Bootstrap and Foundation however Bulma separates itself from some
other frameworks by having no javascript dependencies.
https://bulma.io/

== Parcel
Parcel is a front end application bundler.  There are many projects that do similar work and all are
options for using with Library Weasel.  I've choosen Parcel since it requires little configuration
and currently builds much faster from within a Gradle build than webpack.
https://parceljs.org/
