= Third Party Dependencies

Library Weasel, like much free software, builds on top of already existing tools and libraries.
This page lists out and describes some of the most important of these projects.  Many other projects
are used but below are the ones that almost every Library Weasel plugin are likely to use.

== Kubernetes

== Docker

== Minikube

== Keycloak

== OrientDB

== SparkJava
Spark is a micro framework for the JVM that works well with running JVM microservices on Kubernetes.
http://sparkjava.com/

== Gradle
Gradle is a build tool for the JVM.  I find it easier to work with and extend than other tools such as
maven or ant.  Several projects related to Library Weasel are simply plugins for Gradle.
https://gradle.org/

== Kotlin
Kotlin is an alternative statically typed JVM language that focuses on clean and maintainable code.
Since it comes from JetBrains it also focuses on being toolable and is well supported by the community
edition of IntelliJ IDEA.
https://kotlinlang.org/

== Groovy
Groovy is a scripting language for the JVM that is easy to embed into applications.  It is mainly used
by the library-weasel-developer-script plugin to allow users to run scripts within a Library Weasel
instance.
http://groovy-lang.org/

== KotlinTest/Spock
KotlinTest and Spock are two specification testing frameworks for the JVM.
https://github.com/kotlintest/kotlintest
http://spockframework.org/

== Hyperapp
Hyperapp is a frontend javascript library that focuses on making it easier to create reactive and
maintainable UIs.
https://hyperapp.js.org/

== Bulma
Bulma is a CSS framework similar to Bootstrap and Foundation however Bulma separates itself from some
other frameworks by having no javascript dependencies.
https://bulma.io/

== Parcel
Parcel is a front end application bundler.  There are many projects that do similar work and all are
options for using with Library Weasel.  I've choosen Parcel since it requires little configuration
and currently builds much faster from within a Gradle build than webpack.
https://parceljs.org/
